In [1]:
# Import the Lib
import pandas as pd
import numpy as np

In [2]:
#Reading the dataset
url = 'https://raw.githubusercontent.com/SnehaDebnath678/number_of_order_prediction/refs/heads/main/supplement.csv'
dataset = pd.read_csv(url)
dataset.head()

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,S1,L3,R1,2018-01-01,1,Yes,9,7011.84
1,T1000002,253,S4,L2,R1,2018-01-01,1,Yes,60,51789.12
2,T1000003,252,S3,L2,R1,2018-01-01,1,Yes,42,36868.20
3,T1000004,251,S2,L3,R1,2018-01-01,1,Yes,23,19715.16
4,T1000005,250,S2,L3,R4,2018-01-01,1,Yes,62,45614.52

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188340 entries, 0 to 188339
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ID             188340 non-null  object
 1   Store_id       188340 non-null  int64
 2   Store_Type     188340 non-null  object
 3   Location_Type  188340 non-null  object
 4   Region_Code    188340 non-null  object
 5   Date           188340 non-null  object
 6   Holiday        188340 non-null  int64
 7   Discount       188340 non-null  object
 8   #Order         188340 non-null  int64
 9   Sales          188340 non-null  float64
dtypes: float64(1), int64(3), object(6)
memory usage: 14.4+ MB

In [4]:
dataset.isnull().sum()

ID               0
Store_id         0
Store_Type       0
Location_Type    0
Region_Code      0
Date             0
Holiday          0
Discount         0
#Order           0
Sales            0
dtype: int64

In [5]:
dataset.describe()

            Store_id        Holiday         #Order          Sales
count  188340.000000  188340.000000  188340.000000  188340.000000
mean      183.000000       0.131783      68.205692   42784.327982
std       105.366308       0.338256      30.467415   18456.708302
min         1.000000       0.000000       0.000000       0.000000
25%        92.000000       0.000000      48.000000   30426.000000
50%       183.000000       0.000000      63.000000   39678.000000
75%       274.000000       0.000000      82.000000   51909.000000
max       365.000000       1.000000     371.000000  247215.000000

In [6]:
# pip install plotly
import plotly.express as px

In [7]:
pie = dataset["Store_Type"].value_counts()
store = pie.index
orders = pie.values

fig = px.pie(dataset, values=orders, names=store)
fig.show()

In [8]:
pie2 = dataset["Location_Type"].value_counts()
location = pie2.index
orders = pie2.values

fig = px.pie(dataset, values=orders, names=location)
fig.show()

In [9]:
pie3 = dataset["Discount"].value_counts()
discount = pie3.index
orders = pie3.values

fig = px.pie(dataset, values=orders, names=discount)
fig.show()

In [10]:
pie4 = dataset["Holiday"].value_counts()
holiday = pie4.index
orders = pie4.values

fig = px.pie(dataset, values=orders, names=holiday)
fig.show()

In [11]:
dataset["Discount"] = dataset["Discount"].map({"No": 0,"Yes": 1})

In [12]:
dataset

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,S1,L3,R1,2018-01-01,1,1,9,7011.84
1,T1000002,253,S4,L2,R1,2018-01-01,1,1,60,51789.12
2,T1000003,252,S3,L2,R1,2018-01-01,1,1,42,36868.20
3,T1000004,251,S2,L3,R1,2018-01-01,1,1,23,19715.16
4,T1000005,250,S2,L3,R4,2018-01-01,1,1,62,45614.52
...,...,...,...,...,...,...,...,...,...,...
188335,T1188336,149,S2,L3,R2,2019-05-31,1,1,51,37272.00
188336,T1188337,153,S4,L2,R1,2019-05-31,1,0,90,54572.64
188337,T1188338,154,S1,L3,R2,2019-05-31,1,0,56,31624.56
188338,T1188339,155,S3,L1,R2,2019-05-31,1,1,70,49162.41
188339,T1188340,152,S2,L1,R1,2019-05-31,1,0,47,37977.00

In [13]:
dataset["Store_Type"] = dataset["Store_Type"].map({"S1": 1, "S2": 2,"S3": 3,"S4": 4})

In [14]:
dataset

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,1,L3,R1,2018-01-01,1,1,9,7011.84
1,T1000002,253,4,L2,R1,2018-01-01,1,1,60,51789.12
2,T1000003,252,3,L2,R1,2018-01-01,1,1,42,36868.20
3,T1000004,251,2,L3,R1,2018-01-01,1,1,23,19715.16
4,T1000005,250,2,L3,R4,2018-01-01,1,1,62,45614.52
...,...,...,...,...,...,...,...,...,...,...
188335,T1188336,149,2,L3,R2,2019-05-31,1,1,51,37272.00
188336,T1188337,153,4,L2,R1,2019-05-31,1,0,90,54572.64
188337,T1188338,154,1,L3,R2,2019-05-31,1,0,56,31624.56
188338,T1188339,155,3,L1,R2,2019-05-31,1,1,70,49162.41
188339,T1188340,152,2,L1,R1,2019-05-31,1,0,47,37977.00

In [15]:
dataset["Location_Type"] = dataset["Location_Type"].map({"L1": 1, "L2": 2,"L3": 3,"L4": 4})

In [16]:
dataset

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,1,3.0,R1,2018-01-01,1,1,9,7011.84
1,T1000002,253,4,2.0,R1,2018-01-01,1,1,60,51789.12
2,T1000003,252,3,2.0,R1,2018-01-01,1,1,42,36868.20
3,T1000004,251,2,3.0,R1,2018-01-01,1,1,23,19715.16
4,T1000005,250,2,3.0,R4,2018-01-01,1,1,62,45614.52
...,...,...,...,...,...,...,...,...,...,...
188335,T1188336,149,2,3.0,R2,2019-05-31,1,1,51,37272.00
188336,T1188337,153,4,2.0,R1,2019-05-31,1,0,90,54572.64
188337,T1188338,154,1,3.0,R2,2019-05-31,1,0,56,31624.56
188338,T1188339,155,3,1.0,R2,2019-05-31,1,1,70,49162.41
188339,T1188340,152,2,1.0,R1,2019-05-31,1,0,47,37977.00

In [17]:
x = np.array(dataset[["Store_Type", "Location_Type", "Holiday", "Discount"]])
y = np.array(dataset["#Order"])

In [18]:
x

array([[1., 3., 1., 1.],
       [4., 2., 1., 1.],
       [3., 2., 1., 1.],
       ...,
       [1., 3., 1., 0.],
       [3., 1., 1., 1.],
       [2., 1., 1., 0.]])

In [19]:
y

array([ 9, 60, 42, ..., 56, 70, 47])

In [20]:
# Building the ML model
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [22]:
len(x_train)

150672

In [23]:
# pip install dask[dataframe]

In [24]:
# pip install lightgbm
import lightgbm as ltb
model = ltb.LGBMRegressor()

In [25]:
model.fit(x_train, y_train)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013009 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15
[LightGBM] [Info] Number of data points in the train set: 150672, number of used features: 4
[LightGBM] [Info] Start training from score 68.163401

LGBMRegressor()

In [26]:
y_pred = model.predict(x_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but LGBMRegressor was fitted with feature names

In [27]:
y_pred

array([47.35221153, 97.06885397, 66.57783665, ..., 47.35221153,
       61.74944784, 85.34103588])

In [28]:
y_test

array([ 54, 111,  59, ...,  40,  69,  68])

In [29]:
data = pd.DataFrame(data={"Predicted Orders": y_pred.flatten()})

In [30]:
data

       Predicted Orders
0             47.352212
1             97.068854
2             66.577837
3             85.142955
4             54.451144
...                 ...
37663         66.577837
37664         47.722356
37665         47.352212
37666         61.749448
37667         85.341036

[37668 rows x 1 columns]